name: Deploy CMS

on:
  push:
    branches:
      - main
    paths:
      - 'apps/cms/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build CMS
        run: |
          cd apps/cms
          yarn build
        env:
          NODE_ENV: production

      - name: Transfer artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.yarn,apps/cms/'
          target: 'cms'
          strip_components: 2

      - name: Install dependencies and restart on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/cms
            yarn install --production

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # - name: Deploy to VPS
      #   run: |
      #     echo "Deploying to VPS"
      #     ls ./apps/cms/src -a
      #     rsync -avz --delete -e 'sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no' ./apps/cms/src/public ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:./cms
      #     ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd ~/cms && pm2 restart cms'
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
